DROP TABLE IF EXISTS Measurement;

DROP TABLE IF EXISTS Weather_sensor;

--------------------------------------------------------------------------------

CREATE TABLE Weather_sensor(
      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      sensor_name varchar(30) UNIQUE NOT NULL,
      location varchar(100) NOT NULL,
      added_at timestamp,
      updated_at timestamp,
      added_who varchar(100) NOT NULL
);

CREATE TABLE Measurement(
      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      temperature numeric(6,2) NOT NULL,
      raining bool NOT NULL,
      registered_at timestamp,
      sensor varchar(30) REFERENCES Weather_sensor(sensor_name) NOT NULL
);

---------------------------------------------------------------------------------

SELECT * FROM Weather_sensor;

SELECT * FROM Measurement;
